### ISSUE TITLE
Installing extensions with multiple repos

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash_postgres#213]
**Describe the bug**
I added a second repo to our app. The new repo has different extensions that the original repo (adding timescaledb). When the migrations for the new repo were generated it did not create a migration for the extensions.

**To Reproduce**
Add a new repo to an existing app and generate migrations.

**Expected behavior**
It should create an extensions migration for the new repo.

**Comment by zachdaniel** [comment]
🤔 interesting...is that repo used in any of your resources?

**Comment by rgraff** [comment]
Yes. I think the issue is the extensions exist outside the repo in the resource_snapshots

![CleanShot 2024-02-27 at 16 32 36@2x](https://github.com/ash-project/ash_postgres/assets/8323/7275928f-8121-4347-833b-b11ce7a1a6ae)

**Comment by zachdaniel** [comment]
Ah, right you are. I've got a lot of irons in the fire, and since extensions can be installed/uninstalled with manually created migrations (`mix ecto.gen.migration`) I will leave this one to the community for now. What we need to do is look for that `extensions.json` file, and if it exists, move it into one (any) of the repo scoped directories. Then, when looking for that file, we look in the repo scoped directories.
