### ISSUE TITLE
Non-authorized aggregate in sort / Duplicate join subquery

### ISSUE THREAD

**Issue by vonagam** [ash-project/ash_postgres#446]
Continuing discussing on Discord. The repo for two problems lives here - https://github.com/vonagam/ash_postgres/tree/dupe-repo - run `mix test test/comedy_test.exs` (after applying a migration) to see sql.

Two issues with sorting/selecting aggregate:

1) With `authorize?: true` aggregate for selecting will have policy applied (filter `is_good == true`) while aggregate for ordering will not.

2) With `authorize?: false` both aggregates will be the same but then - why have two identical subqueries? Seems like deduping step missed it.

**Comment by zachdaniel** [comment]
The authorization issue is fixed in `ash` `main`. It's a minor issue that would produce often unpredictable sort results, affects a lesser used feature and doesn't technically leak values, so will not do a CVE for it. Please open a separate issue for the duplicate join query. I likely will not be able to address the duplicate join query any time soon though.

Thank you for the report!
